/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Entite.CPraticien;
import Entite.CMedicament;
import Entite.COffre;
import Service.CTableMedicament;
import Service.CTablePraticien;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author admin
 */
public class CRPanel extends javax.swing.JPanel {
	private Window window;
	private CTablePraticien tablePraticien;
	private ArrayList<CPraticien> listPraticien;
	private CTableMedicament tableMedicament;
	private ArrayList<CMedicament> listMedicament;
	private DefaultTableModel model=new DefaultTableModel();
	
	/**
	 * Creates new form CR
	 */
	public CRPanel() {
		initComponents();
	}
	
	public CRPanel(Window window) {
		this.model.addColumn("Médicament");
		this.model.addColumn("Quantité");
		
		initComponents();
		
		System.out.println("init");
		this.window=window;
		this.tablePraticien=new CTablePraticien(window.bdd);
		this.tableMedicament=new CTableMedicament(window.bdd);
		this.listPraticien=this.tablePraticien.listPraticien();
		this.listMedicament=this.tableMedicament.listMedicamentMin();
		
		//initialize ComboBoxes
		for(int i=0;i<this.listPraticien.size();i++){
			this.jComboBox1.addItem(this.listPraticien.get(i).toString());
			System.out.println(this.listPraticien.get(i).toString());
		}
		JComboBox<String> medComboBox=new JComboBox();
		for(int i=0;i<this.listMedicament.size();i++){
			medComboBox.addItem(this.listMedicament.get(i).getNomCommercial());
		}
		TableColumn medColumn=this.jtableOffre.getColumnModel().getColumn(0);
		medColumn.setCellEditor(new DefaultCellEditor(medComboBox));
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        create = new javax.swing.JPanel();
        labelPraticien = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelBilan = new javax.swing.JLabel();
        labelDateRapport = new javax.swing.JLabel();
        labelMotif = new javax.swing.JLabel();
        textDateRapport = new javax.swing.JTextField();
        textMotif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaBilan = new javax.swing.JTextArea();
        btnCreateRapport = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableOffre = new javax.swing.JTable();
        labelOffre = new javax.swing.JLabel();
        labelResultInfo = new javax.swing.JLabel();
        btnAddOffre = new javax.swing.JButton();
        btnDelRow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        find = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(653, 321));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        create.setBackground(new java.awt.Color(153, 153, 153));

        labelPraticien.setText("Praticien");

        labelBilan.setText("BILAN");

        labelDateRapport.setText("Date Rapport");

        labelMotif.setText("Motif Visite");

        textDateRapport.setText("AAAA-MM-JJ");

        textareaBilan.setColumns(20);
        textareaBilan.setRows(5);
        jScrollPane1.setViewportView(textareaBilan);

        btnCreateRapport.setText("Créer");
        btnCreateRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRapportActionPerformed(evt);
            }
        });

        jtableOffre.setModel(model);
        jScrollPane2.setViewportView(jtableOffre);

        labelOffre.setText("Offres:");

        labelResultInfo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAddOffre.setText("Ajouter une ligne");
        btnAddOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOffreActionPerformed(evt);
            }
        });

        btnDelRow.setText("Supprimer");
        btnDelRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRowActionPerformed(evt);
            }
        });

        btnCancel.setText("Annuler");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createLayout = new javax.swing.GroupLayout(create);
        create.setLayout(createLayout);
        createLayout.setHorizontalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelResultInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createLayout.createSequentialGroup()
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPraticien)
                                    .addComponent(labelDateRapport)
                                    .addComponent(labelMotif)))
                            .addGroup(createLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCreateRapport)
                                    .addComponent(labelBilan))))
                        .addGap(58, 58, 58)
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textDateRapport, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                            .addComponent(textMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancel)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(createLayout.createSequentialGroup()
                            .addComponent(labelOffre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddOffre))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelRow, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
        );
        createLayout.setVerticalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPraticien)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOffre)
                    .addComponent(btnAddOffre))
                .addGap(19, 19, 19)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelRow))
                    .addGroup(createLayout.createSequentialGroup()
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDateRapport)
                            .addComponent(textDateRapport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMotif)
                            .addComponent(textMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBilan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(labelResultInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnCreateRapport)))))
        );

        jTabbedPane1.addTab("Créer un rapport", create);

        find.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout findLayout = new javax.swing.GroupLayout(find);
        find.setLayout(findLayout);
        findLayout.setHorizontalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        findLayout.setVerticalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rechercher un rapport", find);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRapportActionPerformed
        // TODO add your handling code here:
		int numPraticien=-1;
		int numCR;
		ArrayList<COffre> offre=new ArrayList();
		for(int i=0;i<this.listPraticien.size();i++){
			if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase(this.listPraticien.get(i).toString())){
				numPraticien=this.listPraticien.get(i).getNum();
			}
		}
		for(int i=0;i<this.model.getRowCount();i++){
			for(int j=0;j<this.listMedicament.size();j++){
				if(this.jtableOffre.getValueAt(i,0).equals(this.listMedicament.get(j).getNomCommercial()))
					offre.add(new COffre( Integer.parseInt((String)this.jtableOffre.getValueAt(i,1)),this.listMedicament.get(j).getDepotLegal() ));
			}
		}
		if(numPraticien==-1)
			System.out.println("Erreur");
		else if((numCR=window.rapport.createCR(window.login.getVisiteur().getMatricule(),numPraticien,this.textDateRapport.getText(),this.textMotif.getText(),this.textareaBilan.getText(),offre))!=-1){
			this.textDateRapport.setText("AAAA-MM-JJ");
			this.textMotif.setText("");
			this.textareaBilan.setText("");
			for (int i = 0; i < this.model.getRowCount(); i++) {
				this.model.removeRow(i);
			}
			this.labelResultInfo.setText("Votre rapport a bien été enregistré avec le numéro "+numCR);
		}
		System.out.println("create");
    }//GEN-LAST:event_btnCreateRapportActionPerformed

    private void btnAddOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOffreActionPerformed
        // TODO add your handling code here:
		this.model.addRow(new Object[]{});
    }//GEN-LAST:event_btnAddOffreActionPerformed

    private void btnDelRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRowActionPerformed
        // TODO add your handling code here:
		if(this.jtableOffre.getSelectedRow()!=-1)
			this.model.removeRow(this.jtableOffre.getSelectedRow());
    }//GEN-LAST:event_btnDelRowActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
		this.textDateRapport.setText("AAAA-MM-JJ");
		this.textMotif.setText("");
		this.textareaBilan.setText("");
		int nbRow=this.model.getRowCount();
		for (int i = 0; i < nbRow; i++) {
			this.model.removeRow(0);
		}
		this.labelResultInfo.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOffre;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateRapport;
    private javax.swing.JButton btnDelRow;
    private javax.swing.JPanel create;
    private javax.swing.JPanel find;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtableOffre;
    private javax.swing.JLabel labelBilan;
    private javax.swing.JLabel labelDateRapport;
    private javax.swing.JLabel labelMotif;
    private javax.swing.JLabel labelOffre;
    private javax.swing.JLabel labelPraticien;
    private javax.swing.JLabel labelResultInfo;
    private javax.swing.JTextField textDateRapport;
    private javax.swing.JTextField textMotif;
    private javax.swing.JTextArea textareaBilan;
    // End of variables declaration//GEN-END:variables
}
