/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Controller.*;
import IHM.CRPanel;
import IHM.ProductPanel;
import Service.*;
import bdd.CBDD;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author admin
 */
public class Window extends javax.swing.JFrame {
	//BorderLayout layout=new BorderLayout();
	CBDD bdd;
	CLogin login;
	CRapport rapport;
	CProduct product;
	CRPanel cr;
	ProductPanel prod;
	//GridBagLayout layout=new GridBagLayout();

	/**
	 * Creates new form Window
	 */
	public Window() {
		initComponents();
		//cr=new CRPanel(this);
		//prod=new ProductPanel(this);
		this.DynamicPanel.setLayout(new BorderLayout());
		/*GridBagConstraints c=new GridBagConstraints();
		c.gridx=0;
		c.gridy=0;
		this.DynamicPanel.add(cr,c);*/
		this.DynamicPanel.add(cr);
	}
	
	public Window(CLogin login) {
		initComponents();
		this.DynamicPanel.setLayout(new BorderLayout());
		this.login=login;
		this.bdd=login.getTableVisiteur().getBdd();
		this.rapport=new CRapport(new CTableCompteRendu(this.bdd),new CTableOffre(this.bdd));
		
		CTableOffre tableOffre=new CTableOffre(bdd);
		CTableDosage tableDosage=new CTableDosage(bdd);
		CTablePresentation tablePresentation=new CTablePresentation(bdd);
		CTableComposant tableComposant=new CTableComposant(bdd);
		CTablePrescription tablePrescription=new CTablePrescription(bdd,tableDosage);
		CTableMedicament tableMedicament=new CTableMedicament(bdd,tableComposant,tablePrescription,tablePresentation);
		
		this.product=new CProduct(tableMedicament);
		
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		Date date = new Date();
		this.DateLabel.setText(dateFormat.format(date));
		this.NameLabel.setText(login.getName());
		//this.DynamicPanel.setLayout(layout);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnCR = new javax.swing.JButton();
        btnProd = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headPanel.setBackground(new java.awt.Color(204, 204, 204));
        headPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        NameLabel.setText("Name");

        DateLabel.setText("Date");

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 804, Short.MAX_VALUE)
                .addComponent(DateLabel)
                .addContainerGap())
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(DateLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(headPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(204, 204, 204));
        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnCR.setText("Compte rendu");
        btnCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRActionPerformed(evt);
            }
        });

        btnProd.setText("Produits");
        btnProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProd)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRActionPerformed
        // TODO add your handling code here:
		this.DynamicPanel.removeAll();
		this.DynamicPanel.add(cr);
		this.DynamicPanel.repaint();
		this.DynamicPanel.revalidate();
    }//GEN-LAST:event_btnCRActionPerformed

    private void btnProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdActionPerformed
        // TODO add your handling code here:
		this.DynamicPanel.removeAll();
		this.DynamicPanel.add(prod);
		this.DynamicPanel.repaint();
		this.DynamicPanel.revalidate();
    }//GEN-LAST:event_btnProdActionPerformed

	public void init(CRPanel cr, ProductPanel prod){
		this.cr=cr;
		this.prod=prod;
		this.DynamicPanel.add(cr);
	}
	
	/**
	 * @param args the command line arguments
	 */
	//public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		/*try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
*/
		/* Create and display the form */
	/*	java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Window().setVisible(true);
			}
		});
	}*/
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton btnCR;
    private javax.swing.JButton btnProd;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel headPanel;
    // End of variables declaration//GEN-END:variables
}
